export const contasAPagar = [
  {
    ID: 1,
    Valor: '',
    DataVencimento: new Date('2023/07/30'),
    DataCompetencia: new Date('2023/07/30'),
    DataRegistro: new Date('2023/07/30'),
    Ativo: 'Ativo',
    Usuario: 'Admin',
    UltimaAtualizacao: [
      { Data: new Date('2023/07/30') },
      { Usuario: 'Admin' },
      { Mudancas: '' },
    ],
    Descricao: "Conta para pagar...",
    Status: '',
    Juros: 50,
    Multa: 100,
    Desconto: 5,
    IdEmpresa: 1,
    PrevisaoPagamento: '',
    DtPrevistaPagamento: new Date('2023/07/30'),
    NumConta: '',
    Grupo: "Aluguel",
    item: "Casa 1",
  },
  {
    ID: 2,
    Valor: '',
    DataVencimento: new Date('2023/07/30'),
    DataCompetencia: new Date('2023/07/30'),
    DataRegistro: new Date('2023/07/30'),
    Ativo: 'Ativo',
    Usuario: 'Admin',
    UltimaAtualizacao: [
      { Data: new Date('2023/07/30') },
      { Usuario: 'Admin' },
      { Mudancas: '' },
    ],
    Descricao: "Conta para pagar...",
    Status: '',
    Juros: 50,
    Multa: 100,
    Desconto: 5,
    IdEmpresa: 1,
    PrevisaoPagamento: '',
    DtPrevistaPagamento: new Date('2023/07/30'),
    NumConta: '',
    Grupo: "Padaria",
    item: "Pão",
  },
  {
    ID: 3,
    Valor: '',
    DataVencimento: new Date('2023/07/30'),
    DataCompetencia: new Date('2023/07/30'),
    DataRegistro: new Date('2023/07/30'),
    Ativo: 'Ativo',
    Usuario: 'Admin',
    UltimaAtualizacao: [
      { Data: new Date('2023/07/30') },
      { Usuario: 'Admin' },
      { Mudancas: '' },
    ],
    Descricao: "Conta para pagar...",
    Status: '',
    Juros: 50,
    Multa: 100,
    Desconto: 5,
    IdEmpresa: 1,
    PrevisaoPagamento: "",
    DtPrevistaPagamento: new Date('2023/07/30'),
    NumConta: "",
    Grupo: "Carro",
    item: "Manutenção"
  },
];

export const contasPagas = [{
  ID: 1,
  Conta: 'Despesa x',
  ValorPago: 5000,
  MultaPaga: 0,
  DataPagamento: new Date('2023/07/30'),
  DescontoAplicado: 100,
  FormaPagmento: '',
},
];